search property by name
Bidroombv/backoffice-e2e-testing pull request #10
Opened 2021-11-30 13:38 UTC by ewakotanska

2021-11-30 14:54 UTC, wgierczak requested changes

2021-11-30 14:54 UTC, wgierczak commented on backoffice_tests/features/inventory_management_properties_list.feature
> +    Then property with name "Hotel" should be searched
I think this step is not very clear - do we wait for results or some loader informing that search is preformed is enough?

2021-11-30 14:54 UTC, wgierczak commented on backoffice_tests/page_objects/inventory_management_properties_list_page.py
> +        self.second_property_on_list = ElementByCssSelector(".MuiTableRow-root:nth-child(2)")
Same situation as we talked (I don't remember which file it was) - maybe it is better to use some parameter which property we want use. Do you want to do it in this PR or in separate?

2021-11-30 16:33 UTC, ewakotanska commented on backoffice_tests/features/inventory_management_properties_list.feature
> +    Then property with name "Hotel" should be searched
we wait for results, I changed it a little bit

2021-12-02 08:20 UTC, wgierczak approved these changes

2021-12-02 08:27 UTC, merged